name: Combined Workflow

on: [push]

jobs:
  say-hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Обновлено до v4

      - name: Run say-hello
        run: make say-hello

      - name: Checkout repository again
        uses: actions/checkout@v4  # Обновлено до v4

      - name: List files
        run: ls -la

  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Обновлено до v4

      - name: Set up Node.js with caching
        uses: actions/setup-node@v3  # Обновлено до v3
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Check for dependencies lock file
        run: |
          if [ ! -f package-lock.json ] && [ ! -f yarn.lock ]; then
            echo "Dependencies lock file is not found"
            exit 1
          fi

